version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    container_name: go-api-simple_db_1
    volumes:
      #- ./initdb.d:/docker-entrypoint-initdb.d
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - ./mysql/data:/var/lib/mysql
      #- "./mysql/init.sql:/var/lib/mysql"
    network_mode: "host"   
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: IGD
    ports:
      - "3308:3306"
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: pma
  #   restart: always
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: root
  #     PMA_PASSWORD: pass
  #   ports:
  #     - "8081:80"
